### ISSUE TITLE
ETL are wrong on different timezones

### ISSUE THREAD

**Issue by GilDev** [berger89/hmpaisrn#5]
Hi, thanks for the app!
I’m on the Paris timezone, which is UTC+2 (or GMT+2) right now. The app shows UTC times, but then the countdown time before launch takes my UTC+2 time like it’s UTC. That means that a launch that will happen in 2h30min will show in the app as happening in only 30 min.
It would be great if that could be fixed, and if in the settings you could choose to show everything on a specific timezone or on your system timezone, and have proper time calculations based on that.

**Comment by shp-alexander-berger** [comment]
fixed by #7
